### ISSUE TITLE
请问POST方法的KV如何设置？

### ISSUE THREAD

**Issue by Xbigfat** [longforus/api-debugger#1]
如题，在下方 Request Parameter 中填写的都被放到 GET 中拼接起来了，POST 方法里 body 的参数在何处填写呢？

**Comment by Xbigfat** [comment]
误会了，右侧打印会用 ？ 拼接起来，经过实际测试确实已经加入 body 中了，请问作者是否可以增加一个自定义 Header 功能呢，坏笑

**Comment by longforus** [comment]
抱歉 没有注意到,后期闲下来可能会添加,谢谢关注
